
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Herrera
 */
public class MontoAhorrado extends javax.swing.JFrame {

    /**
     * Creates new form MontoAhorrado
     */
    public MontoAhorrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMontoAhorrado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSaldoInicial = new javax.swing.JTextField();
        cmbCalcular = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtResultadoDelMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 24)); // NOI18N
        jLabel1.setText("MONTO AHORRADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel2.setText("Monto Ahorrado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtMontoAhorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAhorradoActionPerformed(evt);
            }
        });
        txtMontoAhorrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoAhorradoKeyTyped(evt);
            }
        });
        getContentPane().add(txtMontoAhorrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));

        jLabel3.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel3.setText("Saldo Inicial");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        txtSaldoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoInicialKeyTyped(evt);
            }
        });
        getContentPane().add(txtSaldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, -1));

        cmbCalcular.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        cmbCalcular.setText("CALCULAR");
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 40));

        cmbBorrar.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        cmbBorrar.setText("BORRAR");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, 50));

        jLabel4.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel4.setText("Resultado Del Monto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 30));

        txtSaldoFinal.setEditable(false);
        getContentPane().add(txtSaldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));

        jLabel5.setFont(new java.awt.Font("JasmineUPC", 2, 24)); // NOI18N
        jLabel5.setText("Saldo Final");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        txtResultadoDelMonto.setEditable(false);
        getContentPane().add(txtResultadoDelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoAhorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAhorradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAhorradoActionPerformed

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        // TODO add your handling code here:
        String  n1, n2, sf, sf1;
        double Mont = 0,Salari=0,resultado = 0,MontoA, SaF;
        
        
        
        if (txtMontoAhorrado.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el MontoAhorrado", "Error",JOptionPane.ERROR_MESSAGE);
        txtMontoAhorrado.requestFocusInWindow();
        
        } else if (txtSaldoInicial.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el Saldo Inicial", "Error",JOptionPane.ERROR_MESSAGE);
        txtSaldoInicial.requestFocusInWindow();
        
        
        }else {
        
        Mont= Double.parseDouble(txtMontoAhorrado.getText());
        Salari =Double.parseDouble(txtSaldoInicial.getText());
        
        }
       
        MontoA= Mont + 0.015;
        sf= String.valueOf(MontoA);
        txtResultadoDelMonto.setText(sf);
        
        
        SaF= Salari+MontoA;
        sf1= String.valueOf(SaF);
        txtSaldoFinal.setText(sf1);
        
       
        
        
            
        
        
    }//GEN-LAST:event_cmbCalcularActionPerformed

    private void txtMontoAhorradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoAhorradoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtMontoAhorradoKeyTyped

    private void txtSaldoInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoInicialKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
          } 
    }//GEN-LAST:event_txtSaldoInicialKeyTyped

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
         txtMontoAhorrado.setText("");
        txtSaldoInicial.setText("");
        txtSaldoFinal.setText("");
        txtResultadoDelMonto.setText("");
        
        txtMontoAhorrado.requestFocusInWindow();
    }//GEN-LAST:event_cmbBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MontoAhorrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MontoAhorrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MontoAhorrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MontoAhorrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MontoAhorrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMontoAhorrado;
    private javax.swing.JTextField txtResultadoDelMonto;
    private javax.swing.JTextField txtSaldoFinal;
    private javax.swing.JTextField txtSaldoInicial;
    // End of variables declaration//GEN-END:variables
}
